use Mix.Config

# Configure your database
config :project, Project.Repo,
  username: "project",
  password: "Bioph7thkuz7Nei3",
  database: "project_prod",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :project, ProjectWeb.Endpoint,
  check_origin: ["project.seablue.site"],
  url: [host: "project-api.seablue.site", port: 5643],
  https: [
    port: 5643,
    certfile: Path.expand("/etc/letsencrypt/live/project.seablue.site/fullchain.pem", __DIR__),
    keyfile: Path.expand("/etc/letsencrypt/live/project.seablue.site/privkey.pem", __DIR__)
  ],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
